### ISSUE TITLE
mac地址无法设置

### ISSUE THREAD

**Issue by sylva2012** [zanjie1999/dingBle#7]
mac地址无法设置，有没有人遇到这个问题然后解决了
`uint8_t bleMac[6] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66};`
这段代码每组地址之间源代码是有空格的，烧录以后MAC地址没有改变，去掉空格一样没用。

**Comment by zanjie1999** [comment]
只支持esp32，至于什么s3，c3没有测试过，架构都不一样了，内部代码变化导致无法复写是很正常的事情，修改使用的并不是开放的api
