### ISSUE TITLE
请问可以成功模拟蓝牙设备，但是点击打卡会提示“蓝牙校验不通过”

### ISSUE THREAD

**Issue by LittleState** [zanjie1999/dingBle#8]
早上烧录完我看能识别到打卡机我就没试，请问现在还能使用吗，大佬…还是说我操作不正确吗

**Comment by zanjie1999** [comment]
只能模拟蓝牙广播，如果你使用的打卡机需要连接蓝牙进行握手通讯的，你可以自己实现，我这里的不需要，只要有广播就可以

**Comment by skysilksock** [comment]
> 只能模拟蓝牙广播，如果你使用的打卡机需要连接蓝牙进行握手通讯的，你可以自己实现，我这里的不需要，只要有广播就可以

请问这个实现的相关知识该在哪里得到补充

**Comment by zanjie1999** [comment]
> > 只能模拟蓝牙广播，如果你使用的打卡机需要连接蓝牙进行握手通讯的，你可以自己实现，我这里的不需要，只要有广播就可以
> 
> 请问这个实现的相关知识该在哪里得到补充

chatgpt.com

**Comment by skysilksock** [comment]
> > > 只能模拟蓝牙广播，如果你使用的打卡机需要连接蓝牙进行握手通讯的，你可以自己实现，我这里的不需要，只要有广播就可以
> > 
> > 
> > 请问这个实现的相关知识该在哪里得到补充
> 
> chatgpt.com

我研究了一下午，应该是模拟的蓝牙设备没有创建正确的服务与特性的原因，我的考勤机设备有一个用于读的特性和用于写的特性，通过对考勤机发送的消息进行处理再返回进行蓝牙校验，现在如何获取考勤机传输的信息对我来说是个难点；不知道我的分析是否正确。

**Comment by qaq112233** [comment]
你是钉钉吗，我这边钉钉是动态蓝牙，没有互相通讯，但是蓝牙广播内容几分钟会变，因此需要实时获取最新的数据。
我正在尝试加入功能，用串口获取广播内容，但还没成功。做好了的话就可以不用每次都编译下载了。
如果你拥有root的设备，推荐使用“模拟蓝牙设备”“蓝牙调试”等模块，hook蓝牙，输入mac和广播数据，即可完成打卡，比这个方便很多。
最完备的方式大致是，在打卡机附近放一个模块，获取广播数据后向服务器上报数据，手机/模块端获取并模拟这个数据

**Comment by zanjie1999** [comment]
> 你是钉钉吗，我这边钉钉是动态蓝牙，没有互相通讯，但是蓝牙广播内容几分钟会变，因此需要实时获取最新的数据。 我正在尝试加入功能，用串口获取广播内容，但还没成功。做好了的话就可以不用每次都编译下载了。 如果你拥有root的设备，推荐使用“模拟蓝牙设备”“蓝牙调试”等模块，hook蓝牙，输入mac和广播数据，即可完成打卡，比这个方便很多。 最完备的方式大致是，在打卡机附近放一个模块，获取广播数据后向服务器上报数据，手机/模块端获取并模拟这个数据

动态但是用固定的能打

**Comment by qaq112233** [comment]
那你们这个挺方便的
我们可能是开启了什么校验，静态的就是会提示“蓝牙校验不通过”

**Comment by RonTang** [comment]
> 在打卡机附近放一个模块，获取广播数据后向服务器上报数据，手机/模块端获取并模拟这个数据

最近再研究这个，即便我获取到打卡机的最新广播包，还是显示打卡机已关闭，可能如您所说 如果你使用的打卡机需要连接蓝牙进行握手通讯的

**Comment by zanjie1999** [comment]
> > 在打卡机附近放一个模块，获取广播数据后向服务器上报数据，手机/模块端获取并模拟这个数据
> 
> 最近再研究这个，即便我获取到打卡机的最新广播包，还是显示打卡机已关闭，可能如您所说 如果你使用的打卡机需要连接蓝牙进行握手通讯的

实际上这直接在打卡机旁边放个手机就完事了，这个最简单，不同的打卡机策略不一样，老打卡机就是固定广播内容就能打，这个程序就是模拟蓝牙广播信标的一种解决方案

**Comment by RonTang** [comment]
感谢回复，我现在就是在打卡机旁边放置了esp32的soc，实时拉取打卡机的广播内容然后通过网络推给蓝牙模拟模块，然后钉钉提示发现设备，但其已关闭哈哈。我估计如您所说，就是需要握手才行。

**Comment by qaq112233** [comment]
> 感谢回复，我现在就是在打卡机旁边放置了esp32的soc，实时拉取打卡机的广播内容然后通过网络推给蓝牙模拟模块，然后钉钉提示发现设备，但其已关闭哈哈。我估计如您所说，就是需要握手才行。

你们这个设备挺先进。我的钉钉还是老的，那个小的圆柱形的，便携最便宜的那款，没有握手要求，只有过几分钟变一次的动态广播

**Comment by zanjie1999** [comment]
> > 感谢回复，我现在就是在打卡机旁边放置了esp32的soc，实时拉取打卡机的广播内容然后通过网络推给蓝牙模拟模块，然后钉钉提示发现设备，但其已关闭哈哈。我估计如您所说，就是需要握手才行。
> 
> 你们这个设备挺先进。我的钉钉还是老的，那个小的圆柱形的，便携最便宜的那款，没有握手要求，只有过几分钟变一次的动态广播

有一说一，这个直接随便抓一次广播一直固定就能用

**Comment by RonTang** [comment]
> > 感谢回复，我现在就是在打卡机旁边放置了esp32的soc，实时拉取打卡机的广播内容然后通过网络推给蓝牙模拟模块，然后钉钉提示发现设备，但其已关闭哈哈。我估计如您所说，就是需要握手才行。
> 
> 你们这个设备挺先进。我的钉钉还是老的，那个小的圆柱形的，便携最便宜的那款，没有握手要求，只有过几分钟变一次的动态广播

不在学习研究了，蓝牙握手协议逆向的话已经超出了新手可以学习的范围哈哈。这设备确实挺先进的，还支持人脸识别。

**Comment by qaq112233** [comment]
> > > 感谢回复，我现在就是在打卡机旁边放置了esp32的soc，实时拉取打卡机的广播内容然后通过网络推给蓝牙模拟模块，然后钉钉提示发现设备，但其已关闭哈哈。我估计如您所说，就是需要握手才行。
> > 
> > 
> > 你们这个设备挺先进。我的钉钉还是老的，那个小的圆柱形的，便携最便宜的那款，没有握手要求，只有过几分钟变一次的动态广播
> 
> 有一说一，这个直接随便抓一次广播一直固定就能用

我试过了，我这的不行，会提示蓝牙校验不通过。两分钟左右变一次。
